Ejercicio 03 - Generar arrays aleatorios del tipo int
djaraweb/gitTarea1 pull request #1
Opened 2024-09-27 23:35 UTC by djaraweb

**Solución al Ejercicio 3 (Tarea1)**

1. Generar un array de int aleatorio de tamaño 500 con valores entre 1 y 1000
2. Cada punto será en una clase, todos los métodos devolverán una colección o un valor int/double:
a. Crear un método que a cada valor se multiplique por 2
b. Crear un método que se obtenga los valores únicos. Por ejemplo: [1,1,2,2,3,4,4,3] -> [1,2,3,4]
c. Crear un método que calcule la suma de todos los valores
d. Crear un método que ordene los valores de menor a mayor

2024-09-27 23:45 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio1.java
> +        Random random = new Random();
final var

2024-09-27 23:46 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio1.java
> +        System.out.println(Arrays.toString(listNumeros));
souf

2024-09-27 23:46 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio1.java
> +        System.out.println(Arrays.toString(arrayValoresDuplicados));
souf

2024-09-27 23:46 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio1.java
> +    static int[] duplicarValoresDeArray(int[] array) {
modificador de acceso

2024-09-27 23:46 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio1.java
> +        for (int i = 0; i < array.length ; i++) {
var i = 0

2024-09-27 23:46 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +        Random random = new Random();
final var

2024-09-27 23:46 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +        System.out.println("****** Generamos un array de int aleatorio de tamaño 500 con valores entre 1 y 1000 ******");
printf

2024-09-27 23:46 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +        System.out.println(Arrays.toString(listNumeros));
printf

2024-09-27 23:46 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +        System.out.println("Total Items filtrados:" + arrayNumerosUnicos.length);
printf

2024-09-27 23:46 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +    static int[] quitarDuplicadosDeArray(int[] numeros) {
modificador de acceso

2024-09-27 23:47 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +    }
mucho te complicas, que colección sirve para filtrar repetidos?

2024-09-27 23:47 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio4.java
> +            for (int j = i+1; j < array.length ; j++) {
var i =0
var j =0

2024-09-27 23:47 UTC, calvarioTeacher31 requested changes
COMENTARIOS APLICAN A TODOS LOS EJERCICIOS

2024-09-27 23:49 UTC, calvarioTeacher31 commented on src/main/java/org/utils/Helpers.java
> +            numeros[i] = generateRandomInt(1000, 1, random);
min y max como parametro
usa faker

2024-09-28 02:59 UTC, djaraweb commented on src/main/java/org/dataint/Ejercicio2.java
> +    }
La colección de Set<>

2024-09-28 03:19 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio1.java
> +        System.out.printf(Arrays.toString(listNumeros));
`printf("El array es: %s", Arrays.toString(...))`
aplica pra todos

2024-09-28 03:19 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +        Set<Integer> listNumeros = new HashSet<>();
`final var set = new HashSet<>();`

2024-09-28 03:19 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +        for (int i = 0; i < n - 1; i++) {
var i = 0

2024-09-28 03:19 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +        for (int i = 0; i < n - 1; i++) {
por qué i < n - 1? debe ser i < n

2024-09-28 03:20 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio3.java
> +       // final int[] listNumeros = {50, 100, 200, 550};
no se deja código comentado

2024-09-28 03:20 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio3.java
> +        }
usa un foreach

2024-09-28 03:20 UTC, calvarioTeacher31 commented on src/main/java/org/dataint/Ejercicio2.java
> +        for (int i = 0; i < n - 1; i++) {
es más usa un foreach

2024-09-28 03:38 UTC, calvarioTeacher31 approved these changes

2024-09-28 03:40 UTC, merged